### ISSUE TITLE
"More than one instance of bitcore-lib found"

### ISSUE THREAD

**Issue by tab00** [trapp/ethereum-bip44#5]
When importing ethereum-bip44 I get the error above.

I think the problem may be avoided if you move bitcore-lib from dependencies to peerDependencies in package.json:

```
"peerDependencies": {
    "bitcore-lib": "^0.15.0"
}
```

**Comment by franciscomemoli** [comment]
I have the same problem here, did you found a way to fix it?

**Comment by zzcandor** [comment]
I have the same problem here ,too .

Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.

**Comment by guerrerocarlos** [comment]
I created a fork that does not import it's own **bitcore** instance, here: https://github.com/guerrerocarlos/ethereum-bip44

Instead you use **bitcore** outside the lib as follows:

Instead of:
```
var wallet = new EthereumBip44.fromPrivateSeed('xprv9s21ZrQH143K4BX2reUURqR54XkNhbNkFhEiRQqFkzu5z7T1dp9eMGozFTgKVu5Bs6R8Wd8BuhcJ3rj3LvzJvkc9uBc5xdhstRfJgcTLsjk');
```

Do:
```
var wallet = new EthereumBip44(bitcore.HDPrivateKey('xprv9s21ZrQH143K4BX2reUURqR54XkNhbNkFhEiRQqFkzu5z7T1dp9eMGozFTgKVu5Bs6R8Wd8BuhcJ3rj3LvzJvkc9uBc5xdhstRfJgcTLsjk'));
```

And the same if you want to use a HDPublicKey, instead of using **EthereumBip44.fromPrivateSeed**, create the **EthereumBip44** instance initializing it with the output from **bitcore.HDPublicKey(...)**.

For more information check the repo's [readme](https://github.com/guerrerocarlos/ethereum-bip44)

Also, this module fork is published in **npm** as [ethereum-bip44-native](https://www.npmjs.com/package/ethereum-bip44-native) and is compatible with AWS Lambda (I removed the compiled dependencies and replaced them with native implementations)
